import numpy as np


# ============================================================
# Physical constants
# ============================================================

PLANCK_CONSTANT = 6.62607015e-34      # J·s
SPEED_OF_LIGHT = 299792458            # m/s


# ============================================================
# Basic conversions
# ============================================================

def db_to_linear(value_db):
    """Convert a dB ratio to linear scale."""
    return 10 ** (value_db / 10)


def wavelength_to_frequency(wavelength_nm):
    """Convert wavelength in nm to optical frequency in Hz."""

    wavelength_m = wavelength_nm * 1e-9

    return SPEED_OF_LIGHT / wavelength_m


# ============================================================
# EDFA ASE model
# ============================================================

def calculate_spontaneous_emission_factor(
    noise_figure_db,
    gain_db
):
    """
    Calculate spontaneous-emission factor n_sp.

    Using:

        F = 2 * n_sp * (1 - 1/G)

    where F and G are linear quantities.
    """

    noise_factor = db_to_linear(noise_figure_db)
    gain_linear = db_to_linear(gain_db)

    n_sp = noise_factor / (
        2 * (1 - 1 / gain_linear)
    )

    return n_sp


def calculate_edfa_ase_power(
    gain_db,
    noise_figure_db,
    wavelength_nm,
    noise_bandwidth_hz
):
    """
    Calculate ASE power generated by one EDFA.

    The ASE power includes both polarization modes:

        P_ASE = 2 * n_sp * h * nu * (G - 1) * B

    Returns ASE power in watts.
    """

    gain_linear = db_to_linear(gain_db)

    frequency_hz = wavelength_to_frequency(
        wavelength_nm
    )

    n_sp = calculate_spontaneous_emission_factor(
        noise_figure_db=noise_figure_db,
        gain_db=gain_db
    )

    ase_power_w = (
        2
        * n_sp
        * PLANCK_CONSTANT
        * frequency_hz
        * (gain_linear - 1)
        * noise_bandwidth_hz
    )

    return ase_power_w

def propagate_ase_link(
    input_ase_w,
    link_name,
    gains_db,
    components,
    network,
    noise_bandwidth_hz,
    include_endpoint_amplifier=True
):
    """
    Propagate ASE noise through one directed fiber link.

    Includes:
    - fiber attenuation of existing ASE
    - amplification of existing ASE
    - newly generated ASE from each EDFA

    Parameters
    ----------
    input_ase_w : float
        ASE noise power entering the link, in watts.

    include_endpoint_amplifier : bool
        If False, an EDFA located exactly at the destination
        node is bypassed for a DROP channel.
    """

    link = network[link_name]

    attenuation_db_per_km = components["fiber"][
        "attenuation_db_per_km"
    ]

    noise_figure_db = components["edfa"][
        "noise_figure_db"
    ]

    wavelength_nm = components["system"][
        "nominal_wavelength_nm"
    ]

    amplifiers = link["amplifiers"]

    if len(amplifiers) != len(gains_db):
        raise ValueError(
            f"{link_name}: number of gains does not match "
            f"number of amplifiers"
        )

    ase_w = input_ase_w
    current_position = 0

    trace = []

    trace.append({
        "stage": f"{link_name} input",
        "position_km": 0,
        "ase_w": ase_w
    })

    for amplifier, gain_db in zip(
        amplifiers,
        gains_db
    ):

        position = amplifier["position_km"]

        # ----------------------------------------------------
        # Fiber attenuation
        # ----------------------------------------------------

        span_length_km = (
            position - current_position
        )

        if span_length_km > 0:

            fiber_loss_db = (
                span_length_km
                * attenuation_db_per_km
            )

            fiber_transmission = (
                10 ** (-fiber_loss_db / 10)
            )

            ase_w *= fiber_transmission

            trace.append({
                "stage": f"Fiber ({span_length_km} km)",
                "position_km": position,
                "ase_w": ase_w
            })

        current_position = position

        # ----------------------------------------------------
        # Endpoint EDFA bypass for DROP channel
        # ----------------------------------------------------

        is_endpoint_amplifier = (
            position == link["length_km"]
        )

        if (
            is_endpoint_amplifier
            and not include_endpoint_amplifier
        ):

            trace.append({
                "stage": "Endpoint EDFA bypassed (DROP)",
                "position_km": position,
                "ase_w": ase_w
            })

            continue

        # ----------------------------------------------------
        # Existing ASE is amplified
        # ----------------------------------------------------

        gain_linear = db_to_linear(
            gain_db
        )

        ase_w *= gain_linear

        # ----------------------------------------------------
        # New ASE generated by this EDFA
        # ----------------------------------------------------

        new_ase_w = calculate_edfa_ase_power(
            gain_db=gain_db,
            noise_figure_db=noise_figure_db,
            wavelength_nm=wavelength_nm,
            noise_bandwidth_hz=noise_bandwidth_hz
        )

        ase_w += new_ase_w

        trace.append({
            "stage": f"EDFA output ({gain_db} dB)",
            "position_km": position,
            "ase_added_w": new_ase_w,
            "ase_w": ase_w
        })

    # --------------------------------------------------------
    # Remaining fiber after last amplifier site
    # --------------------------------------------------------

    remaining_length_km = (
        link["length_km"]
        - current_position
    )

    if remaining_length_km > 0:

        fiber_loss_db = (
            remaining_length_km
            * attenuation_db_per_km
        )

        fiber_transmission = (
            10 ** (-fiber_loss_db / 10)
        )

        ase_w *= fiber_transmission

        trace.append({
            "stage": f"Fiber ({remaining_length_km} km)",
            "position_km": link["length_km"],
            "ase_w": ase_w
        })

    trace.append({
        "stage": f"{link_name} output",
        "position_km": link["length_km"],
        "ase_w": ase_w
    })

    return ase_w, trace

def calculate_snr_db(
    signal_power_w,
    noise_power_w
):
    """
    Calculate SNR in dB.
    """

    if noise_power_w <= 0:
        raise ValueError(
            "Noise power must be greater than zero."
        )

    snr_linear = (
        signal_power_w / noise_power_w
    )

    snr_db = (
        10 * np.log10(snr_linear)
    )

    return snr_db

def calculate_route_ase(
    input_ase_w,
    route,
    gains_by_link,
    components,
    network,
    noise_bandwidth_hz,
    leveling_losses_db=None
):
    """
    Propagate ASE noise through a complete optical route.

    ASE experiences:
    - fiber attenuation
    - EDFA amplification
    - newly generated ASE at each EDFA
    - the same intermediate-node attenuation applied to signal

    Parameters
    ----------
    input_ase_w : float
        ASE noise power entering the first link.

    route : str
        Example: "A-B|B-C"

    gains_by_link : dict
        EDFA gain configuration for every directed fiber.

    noise_bandwidth_hz : float
        ASE integration bandwidth.

    leveling_losses_db : dict or None
        Intermediate-node attenuation derived from the
        signal power-budget calculation.

        Example:
        {
            "A-B -> B-C": 6.0
        }

    Returns
    -------
    ase_w : float
        ASE power at the output of the final fiber,
        before the final DEMUX.

    trace : list
        ASE propagation trace.
    """

    if leveling_losses_db is None:
        leveling_losses_db = {}

    links = route.split("|")

    ase_w = input_ase_w
    trace = []

    for i, link_name in enumerate(links):

        # ----------------------------------------------------
        # Check gain configuration
        # ----------------------------------------------------

        if link_name not in gains_by_link:
            raise ValueError(
                f"No EDFA gain configuration found "
                f"for {link_name}"
            )

        # ----------------------------------------------------
        # Determine whether this is the final link
        # ----------------------------------------------------

        is_last_link = (
            i == len(links) - 1
        )

        # ----------------------------------------------------
        # Propagate ASE through this fiber
        # ----------------------------------------------------

        ase_w, link_trace = propagate_ase_link(
            input_ase_w=ase_w,
            link_name=link_name,
            gains_db=gains_by_link[link_name],
            components=components,
            network=network,
            noise_bandwidth_hz=noise_bandwidth_hz,
            include_endpoint_amplifier=(
                not is_last_link
            )
        )

        # Add link information to trace
        for point in link_trace:

            point_with_link = point.copy()
            point_with_link["link"] = link_name

            trace.append(point_with_link)

        # ----------------------------------------------------
        # Intermediate optical node
        # ----------------------------------------------------

        if not is_last_link:

            next_link = links[i + 1]

            transition_name = (
                f"{link_name} -> {next_link}"
            )

            attenuation_db = (
                leveling_losses_db.get(
                    transition_name,
                    0.0
                )
            )

            # Apply the same attenuation to ASE
            # that was applied to the optical signal.
            attenuation_linear = (
                10 ** (-attenuation_db / 10)
            )

            ase_w *= attenuation_linear

            transit_node = (
                link_name.split("-")[1]
            )

            trace.append({
                "link": transition_name,
                "stage": (
                    f"Node {transit_node} PASS "
                    f"(leveling "
                    f"{attenuation_db:.2f} dB)"
                ),
                "position_km": None,
                "ase_w": ase_w,
                "leveling_attenuation_db": (
                    attenuation_db
                )
            })

    return ase_w, trace